### PR TITLE
Pass the objective constant directly to the solver instead of caching it

### PR DESCRIPTION
**Pull request by rdeits**
Ref: https://github.com/JuliaOpt/LinQuadOptInterface.jl/issues/43

### CODE REVIEW

**Comment by rdeits** [comment]
When this is merged, would you be willing to tag a new release, since `master` now supports LQOI v0.3/MOI v0.5?

**Comment by odow** [comment]
Yip sounds good.

**Comment by rdeits** [comment]
It looks like there's a consistent segfault while precompiling on 32-bit Julia v0.7 and above on windows. Is that a known issue?

**Comment by odow** [comment]
Yes, see https://github.com/JuliaOpt/GLPK.jl/pull/61#issuecomment-412378747

I posted an [issue on discourse](https://discourse.julialang.org/t/gc-error-probable-corruption/13612) but didn't get any hits. Shall I open a Julia issue?

**Comment by rdeits** [comment]
Yeah, I'd open a Julia issue. If it's reproducible it should get fixed pretty quickly.

**Comment by rdeits** [comment]
ok, all green (except the known appveyor issues)

**Pull request merged**
