### PR TITLE
Support newer GLPK (including 4.55) and other things...

### LINKED ISSUE #22: Support newer version of glpk
The version installed on my system is `4.55` and the soname is `libglpk.so.36`. Since the soname is bumped I guess there might have been a ABI breakage. Would be nice to add support for newer version of the library.

### PR DESCRIPTION
**Pull request by yuyichao**
See commit message https://github.com/JuliaOpt/GLPK.jl/commit/4cbd9a7fb49d7465a238882da7fa8996c1376d5c

A few comments:

1. This PR is based on my previous one #23 mainly because of the conflict that needs to be resolved otherwise.
2. None of the real functions are changed. According to [this awesome site](http://upstream-tracker.org/versions/glpk.html), none of the functions/types/constants used by GLPK.jl` is changed.

Fix #22

### CODE REVIEW

**Comment by yuyichao** [comment]
P.S. I have no idea whether this is compatible with `0.2` and the only way I knew it breaks `0.3` is from the CI result.

**Comment by carlobaldassi** [comment]
Given the history of GLPK versions, I'd rather support one version at a time, otherwise it's going to be a mess. For example, this will break with a very high probability with the next version, since there is a minimum version but not a maximum.

There were two new functions introduced in 4.53, one of which changed signature in 4.54 (BTW that upstream-tracker site is really awesome!). These should be supported, or their lack of support documented.

When we bump the GLPK version, we also need a new Homebrew package for that.

**Comment by carlobaldassi** [comment]
Does anyone know what's the standard procedure for adding a glpk455 formula in https://github.com/staticfloat/homebrew-juliadeps? Besides pestering @staticfloat I mean.

**Comment by staticfloat** [comment]
It helps me out if you create the formula yourself and open a PR, so that I can just merge and see how the buildbots fare.  For a simple version bump, the procedure is not hard; change the download URL (and mirror URL, if applicable), update the checksum line (we do `sha256` now, so [this line](https://github.com/staticfloat/homebrew-juliadeps/blob/eb0a89f61a1e6ba74595a777c9aa23e23730dadf/glpk454.rb#L7), should instead be `sha256 a1b2c3d4....`, because `sha1` is old) and remove any checksums inside of the `bottle do` stanza.  (E.g. delete [these lines](https://github.com/staticfloat/homebrew-juliadeps/blob/eb0a89f61a1e6ba74595a777c9aa23e23730dadf/glpk454.rb#L12-L15))

Base any pull requests against the `staging` branch, and I can pretty much just merge immediately, run it on the buildbots, and see what happens.

**Comment by carlobaldassi** [comment]
Thanks, will do.

**Comment by yuyichao** [comment]
The approach I'm taking here is to support the `4.52` interface while allowing compatible versions to be loaded at runtime if it is available on the system. I have thought about adding a maximum version as well but I'm not familiar with how much breakage a new version of glpk usually introduce so I wasn't sure if it is necessary.

IMHO, as long as a few versions are known to provide an interface capatible with the one needed, it would be nice to support them. It would be nice to add support for that (with a version range to be determined)

I currently have no objection for bumping the requirement/default for GLPK version although I guess Debian maintainers might complain?

**Comment by carlobaldassi** [comment]
The issue is that the GLPK maintainers do things like [removing symbols](http://upstream-tracker.org/compat_reports/glpk/4.50_to_4.51/abi_compat_report.html#Withdrawn) or [changing the API](http://upstream-tracker.org/compat_reports/glpk/4.53_to_4.54/abi_compat_report.html#Medium_Risk_Problems) from one version to the next, quite frequently. This will result in segfaults from `ccall`, which need to be avoided. Especially because there will be no way to switch to manual compilation if breakage occurs.

Allowing a higher version, if compatible, is good, but we definitely need a maximum version check (which we can bump when new versions come out).

**Comment by yuyichao** [comment]
> Allowing a higher version, if compatible, is good, but we definitely need a maximum version check (which we can bump when new versions come out).

This is exactly what I've thought about and if the upstream breaks thing quite often, I guess it is necessary as well.

According to both the upstream tracker and my local test, the `4.52` api and abi should be supported on all versions from `4.52` to `4.55`. I'll just add a check for that then.

**Comment by staticfloat** [comment]
It's pretty reasonable to ask the developers to include some kind of `get_glpk_version()` or something, which you can then use to tailor your `ccall` invocations.  We recently convinced the `libnettle` guys to do something similar.

**Comment by yuyichao** [comment]
@staticfloat There is such a function and is already used by this package. I think what @carlobaldassi is worrying about is that we don't know if the next version will break anything, which might be quite common for `glpk`.

**Comment by yuyichao** [comment]
Max version check added.

**Comment by carlobaldassi** [comment]
Great, let me check on julia 0.2.

**Comment by yuyichao** [comment]
@carlobaldassi I'm pretty sure `util/parse_header.jl` will probably not work even on `0.3` but I hope it doesn't matter since it is just used to generate a source file at develop time anyway...

**Comment by carlobaldassi** [comment]
Yep, works great.
(yeah I noticed about `parse_header.jl` using the `Tuple` syntax, but that's not an issue, it's for maintainers only.)

**Pull request merged**
