### PR TITLE
Updates for MOI 0.6

### PR DESCRIPTION
**Pull request by IssamT**

### CODE REVIEW

**Comment by tkoolen** [comment]
Again I'd very much appreciate a new version tag before this gets merged (at current master).

**Comment by odow** [comment]
Provided #56 passes CI, I'll merge that and then tag a release before we merge this.

**Comment by tkoolen** [comment]
Thanks!

**Comment by odow** [comment]
@IssamT is this good to merge?

**Comment by IssamT** [comment]
Yes, thanks.

**Pull request merged**
