### PR TITLE
More dep warn fixes, remove 0.3, add 0.5 support

### PR DESCRIPTION
**Pull request by ranjanan**
There's this one depwarn I'm not able to identify:

```
WARNING: deprecated syntax "param.(s) = ...".
Use "setfield!(param, s, ...)" instead.
```

Do you know where this is coming from?

### CODE REVIEW

**Comment by carlobaldassi** [comment]
> Do you know where this is coming from?

It's these two lines:
https://github.com/JuliaOpt/GLPK.jl/blob/a3e11cbe6290f6dd2f154468e39e404039806adb/src/GLPK.jl#L268
https://github.com/JuliaOpt/GLPK.jl/blob/a3e11cbe6290f6dd2f154468e39e404039806adb/src/GLPK.jl#L272

They need to be replaced with `setfield!(param, i, convert(t, val))` and `getfield(param, Symbol(field_name))` I guess.

**Comment by ranjanan** [comment]
@carlobaldassi Thanks!

**Comment by ranjanan** [comment]
Woohoo, passes now!

**Comment by carlobaldassi** [comment]
It seems from Travis/Appveyor outputs that "nightly" is now using "0.6-dev". Could you add also "0.5" in the versions to be tested?

**Comment by carlobaldassi** [comment]
Thanks!

**Comment by ranjanan** [comment]
@carlobaldassi Would you mind tagging a new release please?

**Pull request merged**
