### PR TITLE
Fix build on Julia 1.0.

### LINKED ISSUE #62: Build fails on Julia 1.0 on MacOS
Building GLPK ───→ `~/.julia/packages/GLPK/thMVo/deps/build.log`
┌ Error: Error building `GLPK`: 
│ ERROR: LoadError: MethodError: no method matching replace(::String, ::String, ::String)
│ Closest candidates are:
│   replace(::String, !Matched::Pair{#s55,B} where B where #s55<:AbstractChar; count) at strings/util.jl:414
│   replace(::String, !Matched::Pair{#s52,B} where B where #s52<:Union{Tuple{Vararg{AbstractChar,N} where N}, Set{#s49} where #s49<:AbstractChar, AbstractArray{#s50,1} where #s50<:AbstractChar}; count) at strings/util.jl:419
│   replace(::String, !Matched::Pair; count) at strings/util.jl:423
│   ...
│ Stacktrace:
│  [1] top-level scope at none:0
│  [2] include at ./boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at ./loading.jl:1038
│  [4] include(::Module, ::String) at ./sysimg.jl:29
│  [5] include(::String) at ./client.jl:388
│  [6] top-level scope at none:0
│ in expression starting at /Users/arora/.julia/packages/GLPK/thMVo/deps/build.jl:10
└ @ Pkg.Operations ~/src/julia/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068

### PR DESCRIPTION
**Pull request by tkoolen**
Fixes #62. Tested locally on OSX with Julia 1.0.

### CODE REVIEW

**Comment by tkoolen** [comment]
http://ftp.gnu.org/ is down.

**Comment by odow** [comment]
I just merged https://github.com/JuliaOpt/GLPK.jl/pull/61 so you will need to update the travis and appveyor

**Comment by tkoolen** [comment]
Failure on Travis 1.0 is https://github.com/JuliaPackaging/BinDeps.jl/issues/375. Needs https://github.com/JuliaLang/METADATA.jl/pull/16899.

**Comment by tkoolen** [comment]
BinDeps tag is in, restarted build.

**Comment by tkoolen** [comment]
Appveyor failure is the same as https://github.com/JuliaOpt/GLPK.jl/pull/61#issuecomment-412378747.

Good to go?

**Comment by odow** [comment]
Any idea about the 32-bit failure? Should I post on discourse? It's a bit of a fools errand without being able to reproduce.

**Comment by tkoolen** [comment]
No idea, sorry. Discourse could be a good idea.

**Pull request merged**
