### PR TITLE
Fix handling of setting variable bounds. 

### PR DESCRIPTION
**Pull request by odow**
We need to loop through and collect upper and lower terms, otherwise we can end up trying to set
variable bounds with lower > upper.

See also https://github.com/JuliaOpt/LinQuadOptInterface.jl/pull/66

- [x] Needs test

### CODE REVIEW

**Comment by blegat** [comment]
What do you do in case with lower > upper ?

**Comment by odow** [comment]
Good point, we should throw an error, although probably at the MOI level

**Comment by blegat** [comment]
In MathProgBase, we had a special treatment that was added [here](https://github.com/JuliaOpt/GLPKMathProgInterface.jl/pull/34)

**Comment by odow** [comment]
Okay so we have two options:
1. Add a check prior to solve for invalid bounds. 
2. Perform no check, and allow GLPK to return `TerminationStatus = OtherError` and print a nice warning saying that there are invalid bounds.

Currently, this PR does option 1. For simplicity, the current check is O(n+m) where n is the number of variables and m is the number of constraints. We could do better by recording invalid bounds at the creation and modification steps. I haven't gone that route as the bigger question is whether this check is worth it.

**Comment by odow** [comment]
Okay, now we just disable the preemptive check (maybe it should be off by default???) and then handle the status properly.

**Comment by odow** [comment]
Bump on the reviews.

**Pull request merged**
